"""
Centralized configuration module for EZ Expense application.

This module provides a single source of truth for configuration values
that need to be shared across different components of the application.
"""

import os

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Debug and development settings
DEBUG = os.getenv("DEBUG", "False").lower() == "true"
FLASK_DEBUG = os.getenv("FLASK_DEBUG", "False").lower() == "true"
DEBUG_LOG_TARGET = os.getenv("DEBUG_LOG_TARGET", "ez-expense.log").strip('"')

# Port configurations
BROWSER_PORT = int(os.getenv("PORT", 9222))
FRONTEND_PORT = int(os.getenv("FRONTEND_PORT", 5001))

# Application URLs
EXPENSE_APP_URL = "myexpense.operations.dynamics.com"
FRONTEND_URL = f"http://localhost:{FRONTEND_PORT}"

# Flask configuration
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-in-production")
MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16MB max file size
ALLOWED_EXTENSIONS = {"csv", "pdf", "png", "jpg", "jpeg", "gif"}

EXPENSE_CATEGORIES = [
    "Admin Services - Misc.",
    "Airfare",
    "Airline Fees",
    "Broadband - Home",
    "Car | Fuel & Maintenance",
    "Car | Mileage",
    "Car Rental",
    "Catering",
    "Computer Services",
    "Courier/Shipping/Freight",
    "Dues",
    "Empl Benefits-Sport/Social/Gym",
    "Employee Benefits - Misc",
    "Employee Gifts <£50",
    "Employee Morale",
    "Entertainment - external",
    "Event Incidentals",
    "FX Diff & Bank Fees",
    "Gift | external",
    "Government Official",
    "Ground Transportation",
    "Hardware (Supplies General)",
    "Hardware Dev (Prod Dev-Other)",
    "Hotel",
    "Infrastructure & Ops Support",
    "Internet/Online Fees - Travel",
    "Lab Reference Material",
    "Lab Supplies",
    "Meals | Employee Morale",
    "Meals | Employee Travel",
    "Membership & Dues (Advertising",
    "Mobile/Cellular Phone",
    "Office Equipment/Hardware",
    "Office Supplies",
    "Other Product Development",
    "Parking",
    "Passport/Visa Fees",
    "Postage",
    "Prof Learning (EE dev & train)",
    "Professional Subscriptions",
    "Recruiting",
    "Relocation Expenses",
    "Seminar/Course Fees",
    "T&E Other",
    "Telecommunications-Other",
    "Telephone/Fax",
    "Tips/Gratuities",
    "Tolls/Road Charges",
    "Tuition/Training Reimbursement",
    "Volunteer Event Items - Non US",
    "Volunteer Event Items - US",
]

CURRENCY_CODES = [
    "AFN",
    "ALL",
    "AMD",
    "AOA",
    "ARS",
    "AUD",
    "AWG",
    "AZN",
    "DZD",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BHD",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BRL",
    "BSD",
    "BTC",
    "BTN",
    "BWP",
    "BYR",
    "BZD",
    "GBP",
    "CAD",
    "CDF",
    "CLF",
    "CLP",
    "CNY",
    "COP",
    "CRC",
    "CUC",
    "CUP",
    "CVE",
    "CZK",
    "HRK",
    "KHR",
    "KMF",
    "KYD",
    "XAF",
    "XOF",
    "XPF",
    "DJF",
    "DKK",
    "DOP",
    "EGP",
    "ERN",
    "ETB",
    "EUR",
    "XCD",
    "FJD",
    "FKP",
    "GEL",
    "GGP",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "XAU",
    "HKD",
    "HNL",
    "HTG",
    "HUF",
    "IDR",
    "ILS",
    "INR",
    "IQD",
    "IRR",
    "ISK",
    "JEP",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KGS",
    "KWD",
    "KZT",
    "LAK",
    "LBP",
    "LRD",
    "LSL",
    "LTL",
    "LVL",
    "LYD",
    "IMP",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MMK",
    "MNT",
    "MOP",
    "MRO",
    "MUR",
    "MVR",
    "MWK",
    "MXN",
    "MYR",
    "MZN",
    "ANG",
    "BYN",
    "KPW",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "TWD",
    "OMR",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RUB",
    "RWF",
    "CHF",
    "KRW",
    "LKR",
    "RSD",
    "SAR",
    "SBD",
    "SCR",
    "SDG",
    "SEK",
    "SGD",
    "SHP",
    "SLL",
    "SOS",
    "SRD",
    "STD",
    "SVC",
    "SYP",
    "SZL",
    "WST",
    "XAG",
    "XDR",
    "ZAR",
    "THB",
    "TJS",
    "TMT",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TZS",
    "AED",
    "UAH",
    "UGX",
    "USD",
    "UYU",
    "UZS",
    "VEF",
    "VND",
    "VUV",
    "YER",
    "ZMK",
    "ZMW",
    "ZWL",
]
